# Generated by Django 5.0.4 on 2024-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_vido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploaded_to_youtube',
        ),
        migrations.AlterField(
            model_name='video',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=50),
        ),
    ]
